import { describe, expect, test } from 'bun:test';

import {
  SECTOR_SPECIAL_CLOSE_DOOR_30,
  SECTOR_SPECIAL_DAMAGE_END,
  SECTOR_SPECIAL_DAMAGE_NUKAGE,
  SECTOR_SPECIAL_DAMAGE_SLIME,
  SECTOR_SPECIAL_DAMAGE_SUPER,
  SECTOR_SPECIAL_LIGHT_FIRE_FLICKER,
  SECTOR_SPECIAL_LIGHT_FLICKER,
  SECTOR_SPECIAL_LIGHT_OSCILLATE,
  SECTOR_SPECIAL_LIGHT_STROBE_FAST,
  SECTOR_SPECIAL_LIGHT_STROBE_FAST_DAMAGE,
  SECTOR_SPECIAL_LIGHT_STROBE_SLOW,
  SECTOR_SPECIAL_LIGHT_SYNC_STROBE_FAST,
  SECTOR_SPECIAL_LIGHT_SYNC_STROBE_SLOW,
  SECTOR_SPECIAL_NORMAL,
  SECTOR_SPECIAL_RAISE_DOOR_5MIN,
  SECTOR_SPECIAL_SECRET,
  VANILLA_SECTOR_DAMAGE_END,
  VANILLA_SECTOR_DAMAGE_NUKAGE,
  VANILLA_SECTOR_DAMAGE_SLIME,
  VANILLA_SECTOR_DAMAGE_STROBE_HURT,
  VANILLA_SECTOR_DAMAGE_SUPER,
  VANILLA_SECTOR_DAMAGE_TIC_INTERVAL,
} from '../../../src/ai/implement-sector-special-effects.ts';

describe('vanilla sector specials enum', () => {
  test('damage tic interval = 32', () => {
    expect(VANILLA_SECTOR_DAMAGE_TIC_INTERVAL).toBe(32);
  });

  test('damage rates: nukage 10, slime 5, strobe 20, end 20, super 20', () => {
    expect(VANILLA_SECTOR_DAMAGE_NUKAGE).toBe(10);
    expect(VANILLA_SECTOR_DAMAGE_SLIME).toBe(5);
    expect(VANILLA_SECTOR_DAMAGE_STROBE_HURT).toBe(20);
    expect(VANILLA_SECTOR_DAMAGE_END).toBe(20);
    expect(VANILLA_SECTOR_DAMAGE_SUPER).toBe(20);
  });

  test('sector special enum values 0..17', () => {
    expect(SECTOR_SPECIAL_NORMAL).toBe(0);
    expect(SECTOR_SPECIAL_LIGHT_FLICKER).toBe(1);
    expect(SECTOR_SPECIAL_LIGHT_STROBE_FAST).toBe(2);
    expect(SECTOR_SPECIAL_LIGHT_STROBE_SLOW).toBe(3);
    expect(SECTOR_SPECIAL_LIGHT_STROBE_FAST_DAMAGE).toBe(4);
    expect(SECTOR_SPECIAL_DAMAGE_NUKAGE).toBe(5);
    expect(SECTOR_SPECIAL_DAMAGE_SLIME).toBe(7);
    expect(SECTOR_SPECIAL_LIGHT_OSCILLATE).toBe(8);
    expect(SECTOR_SPECIAL_SECRET).toBe(9);
    expect(SECTOR_SPECIAL_CLOSE_DOOR_30).toBe(10);
    expect(SECTOR_SPECIAL_DAMAGE_END).toBe(11);
    expect(SECTOR_SPECIAL_LIGHT_SYNC_STROBE_SLOW).toBe(12);
    expect(SECTOR_SPECIAL_LIGHT_SYNC_STROBE_FAST).toBe(13);
    expect(SECTOR_SPECIAL_RAISE_DOOR_5MIN).toBe(14);
    expect(SECTOR_SPECIAL_DAMAGE_SUPER).toBe(16);
    expect(SECTOR_SPECIAL_LIGHT_FIRE_FLICKER).toBe(17);
  });
});
