import { mkdir } from 'node:fs/promises';

import { FINAL_PLAN_LANES, FINAL_PLAN_STEP_COUNT, FINAL_PLAN_STEPS, type FinalPlanStep } from './planData.ts';

const GENERATED_NOTICE = '<!-- Generated by plan_final/generate-plan-files.ts. Edit planData.ts, then regenerate. -->';
const TRACKED_DIRECTORY_PLACEHOLDER = 'tracked directory placeholder\n';

function bulletList(values: readonly string[]): string {
  if (values.length === 0) {
    return '- none';
  }

  return values.map((value) => `- ${value}`).join('\n');
}

function slugify(value: string): string {
  return value.toLowerCase().replaceAll(/[^a-z0-9]+/g, '-').replaceAll(/^-|-$/g, '');
}

function stepPath(step: FinalPlanStep): string {
  return `plan_final/steps/${step.id}-${slugify(step.title)}.md`;
}

function stepMarkdown(step: FinalPlanStep): string {
  const focusedTest = step.testFiles[0] ?? 'test/plan_final/validate-plan.test.ts';

  return `${GENERATED_NOTICE}

# [ ] STEP ${step.id}: ${step.title}

## id

${step.id}

## lane

${step.lane}

## title

${step.title}

## goal

${step.goal}

## prerequisites

${bulletList(step.prerequisites)}

## parallel-safe-with

${bulletList(step.parallelSafeWith)}

## write lock

${bulletList(step.writeLock)}

## read-only paths

${bulletList(step.readOnlyPaths)}

## research sources

${bulletList(step.researchSources)}

## expected changes

${bulletList(step.expectedChanges)}

## test files

${bulletList(step.testFiles)}

## verification commands

- \`bun run format\`
- \`bun test ${focusedTest}\`
- \`bun test\`
- \`bun x tsc --noEmit --project tsconfig.json\`

## progress log

- Append before the first read: \`plan_final/progress/${step.lane}/${step.id}.md\`.
- Append after every read group, edit group, failed command, fix attempt, passing command sequence, commit, pull/rebase, and push.
- Preserve the log on block or failure so the next agent can resume without guessing.

## completion criteria

- The focused test proves the behavior or inventory result for this exact step.
- \`bun run format\`, focused \`bun test ${focusedTest}\`, \`bun test\`, and \`bun x tsc --noEmit --project tsconfig.json\` all pass in that order.
- Any failure is fixed in this same step and the full verification sequence is rerun from the beginning.
- The step is not marked complete, committed, or pushed while any verification command is failing.
- Files are staged explicitly by path, committed with a Conventional Commit, and pushed directly with local git commands.

## final evidence

- Write \`plan_final/evidence/${step.id}.json\` with commands, changed paths, and zero known failures.
- Write \`plan_final/status/${step.id}.json\` only after verification passes; status must not claim completion for failing tests.
- Include the pushed commit SHA in the progress log after \`git push\` verifies the remote contains it.
`;
}

function checklistMarkdown(): string {
  const lines: string[] = [
    GENERATED_NOTICE,
    '',
    '# Master Checklist',
    '',
    `- Total steps: ${FINAL_PLAN_STEP_COUNT}`,
    '- Runtime target: `bun run doom.ts`',
    '- Rule: choose the first unchecked step whose prerequisites are complete in the assigned lane.',
    '- Completion rule: a step is complete only when `bun run format`, focused `bun test`, full `bun test`, and `bun x tsc --noEmit --project tsconfig.json` all pass.',
    '',
  ];

  for (const lane of FINAL_PLAN_LANES) {
    lines.push(`## ${lane.lane}`, '');
    for (const step of FINAL_PLAN_STEPS.filter((candidate) => candidate.lane === lane.lane)) {
      const prerequisites = step.prerequisites.length === 0 ? 'none' : step.prerequisites.join(', ');
      lines.push(`- [ ] \`${step.id}\` \`${step.title}\` | lane: \`${step.lane}\` | prereqs: \`${prerequisites}\` | file: \`${stepPath(step)}\``);
    }
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

function parallelWorkMarkdown(): string {
  const lines = [
    GENERATED_NOTICE,
    '',
    '# Parallel Work',
    '',
    '| lane | work | owns | blocked by |',
    '| --- | --- | --- | --- |',
  ];

  for (const lane of FINAL_PLAN_LANES) {
    const owns = lane.owns.map((path) => `\`${path}\``).join('<br>');
    const blockedBy = lane.lane === 'acceptance' ? 'runtime and oracle gates' : 'listed step prerequisites only';
    lines.push(`| \`${lane.lane}\` | ${lane.description} | ${owns} | ${blockedBy} |`);
  }

  lines.push('');
  lines.push('Agents may run different lanes in parallel only when their selected step write locks do not overlap.');
  lines.push('');

  return `${lines.join('\n')}\n`;
}

function dependencyGraphMarkdown(): string {
  return `${GENERATED_NOTICE}

# Dependency Graph

## Gates

| gate | depends on | proof |
| --- | --- | --- |
| G0 control center | 00-governance | \`bun test test/plan_final/validate-plan.test.ts\` and \`bun run plan_final/validate-plan.ts\`. |
| G1 current truth | 01-current-state | inventories prove real gaps without claiming parity. |
| G2 live oracles | 02-oracle | pending fixtures are replaced by live reference evidence. |
| G3 clean launch | 03-launch-host-input, 04-runtime-core, 05-wad-assets, 07-ui | \`bun run doom.ts\` reaches title loop. |
| G4 playable E1M1 | 06-render, 08-map-world, 09-player-weapons-items, 10-ai-specials, 11-audio | scripted movement, use, pickup, combat, and death windows match reference. |
| G5 persistence and demos | 12-save-config-demo | save/load bytes and DEMO1/2/3 checkpoints match reference. |
| G6 final parity | 13-acceptance | final side-by-side report has zero differences and no pending evidence. |

## Rule

No acceptance gate may pass from manifest inspection alone. Final proof must execute \`bun run doom.ts\` and compare live evidence.
`;
}

function readmeMarkdown(): string {
  return `${GENERATED_NOTICE}

# plan_final

Final control center for finishing the TypeScript/Bun DOOM parity target.

## Mission

\`bun run doom.ts\` must launch a complete vanilla DOOM experience for the local shareware DOOM 1.9 target and produce zero-difference live side-by-side evidence against the local reference executable.

## Current Truth

- \`doom.ts\` began as a skeleton entrypoint.
- \`src/main.ts\` is a gameplay-first launcher and is not protected API.
- Prior plans are prior art, not final proof.
- Pending or manifest-only oracle evidence must be replaced by live captures.

## Completion Rule

A step is complete only when all commands pass in order:

1. \`bun run format\`
2. focused \`bun test <path>\`
3. \`bun test\`
4. \`bun x tsc --noEmit --project tsconfig.json\`

Any failure must be fixed in the same step, logged, and the full command sequence rerun from the beginning. Do not commit, push, or mark a step complete while anything is failing.

## Publishing

Use local git only. Stage explicit paths, commit with Conventional Commits, and push directly. Do not open pull requests and do not use GitHub API tooling.
`;
}

function promptMarkdown(): string {
  return `${GENERATED_NOTICE}

# Ralph Loop Prompt

Continue the Ralph loop using \`plan_final/\` as the only active execution control center.

1. Read \`AGENTS.md\`, \`plan_final/PROMPT.md\`, \`plan_final/MASTER_CHECKLIST.md\`, and the selected step file.
2. Select exactly one step. If \`RLP_LANE\` is set, select the first eligible step in that lane only. Otherwise use \`bun run plan_final/select-step.ts\`.
3. Before reading implementation files, append a start entry to \`plan_final/progress/<lane>/<step-id>.md\`.
4. Read only the paths listed in the selected step.
5. Change only the selected step write lock and expected changes.
6. Add or update the focused test.
7. Run \`bun run format\`, focused \`bun test\`, full \`bun test\`, and typecheck in order.
8. If any command fails, log it, fix it, and rerun the full sequence from the beginning.
9. After all commands pass, stage explicit paths, commit, push, and log the pushed commit SHA.

End with:

\`\`\`
RLP_STATUS: COMPLETED|BLOCKED|NO_ELIGIBLE_STEP
RLP_STEP_ID: <id or NONE>
RLP_LANE: <lane or NONE>
RLP_FILES_CHANGED: <semicolon-separated paths or NONE>
RLP_TEST_COMMANDS: <semicolon-separated commands or NONE>
RLP_REASON: <one-line reason>
\`\`\`
`;
}

function prePromptMarkdown(): string {
  return `${GENERATED_NOTICE}

# Pre Prompt

Use Bun only. Do not use npm, yarn, pnpm, npx, node, jest, vitest, mocha, ts-node, or tsx.

This plan is not complete because a checklist says so. It is complete only when executable tests and live side-by-side evidence prove \`bun run doom.ts\` matches the reference.
`;
}

function stepTemplateMarkdown(): string {
  return `${GENERATED_NOTICE}

# [ ] STEP <id>: <title>

## id

<id>

## lane

<lane>

## title

<title>

## goal

<one exact outcome>

## prerequisites

- <step ids or none>

## parallel-safe-with

- <safe lanes or constraints>

## write lock

- <paths>

## read-only paths

- <paths>

## research sources

- <paths or reference authority>

## expected changes

- <paths>

## test files

- <focused test path>

## verification commands

- \`bun run format\`
- \`bun test <focused test path>\`
- \`bun test\`
- \`bun x tsc --noEmit --project tsconfig.json\`

## progress log

- Append to \`plan_final/progress/<lane>/<step-id>.md\` throughout the step.

## completion criteria

- All verification commands pass in order.
- Failures are fixed, not hidden or skipped.
- The verified change is committed and pushed.

## final evidence

- \`plan_final/evidence/<step-id>.json\`
- \`plan_final/status/<step-id>.json\`
`;
}

async function writeText(path: string, text: string): Promise<void> {
  await Bun.write(path, text);
}

export async function generatePlanFiles(): Promise<void> {
  await mkdir('plan_final/steps', { recursive: true });
  await mkdir('plan_final/status', { recursive: true });
  await mkdir('plan_final/progress/governance', { recursive: true });
  await mkdir('plan_final/evidence', { recursive: true });
  await mkdir('plan_final/lane_locks', { recursive: true });

  await writeText('plan_final/evidence/.gitkeep', TRACKED_DIRECTORY_PLACEHOLDER);
  await writeText('plan_final/lane_locks/.gitkeep', TRACKED_DIRECTORY_PLACEHOLDER);
  await writeText('plan_final/status/.gitkeep', TRACKED_DIRECTORY_PLACEHOLDER);

  await writeText('plan_final/README.md', readmeMarkdown());
  await writeText('plan_final/PROMPT.md', promptMarkdown());
  await writeText('plan_final/PRE_PROMPT.md', prePromptMarkdown());
  await writeText('plan_final/STEP_TEMPLATE.md', stepTemplateMarkdown());
  await writeText('plan_final/PARALLEL_WORK.md', parallelWorkMarkdown());
  await writeText('plan_final/DEPENDENCY_GRAPH.md', dependencyGraphMarkdown());
  await writeText('plan_final/MASTER_CHECKLIST.md', checklistMarkdown());

  for (const lane of FINAL_PLAN_LANES) {
    await mkdir(`plan_final/progress/${lane.lane}`, { recursive: true });
    if (lane.lane !== 'governance') {
      await writeText(`plan_final/progress/${lane.lane}/.gitkeep`, TRACKED_DIRECTORY_PLACEHOLDER);
    }
  }

  for (const stepDefinition of FINAL_PLAN_STEPS) {
    await writeText(stepPath(stepDefinition), stepMarkdown(stepDefinition));
  }

  await writeText(
    'plan_final/progress/governance/00-001.md',
    [
      '# 00-001 create-final-control-center',
      '',
      '- Started control-center creation.',
      '- Generated plan files, lane progress directories, and step files from planData.ts.',
      '- Focused verification target: test/plan_final/validate-plan.test.ts.',
      '',
    ].join('\n'),
  );
}

if (import.meta.main) {
  await generatePlanFiles();
}
