/**
 * Asset and license boundary policy for the DOOM Codex project.
 *
 * Every reference bundle file is classified by license category and
 * redistribution policy.  Path constants lock the read-only reference
 * bundle root and the writable codex workspace root per D-006.
 *
 * @example
 * ```ts
 * import { ASSET_BOUNDARIES, REFERENCE_BUNDLE_PATH } from "../src/reference/policy.ts";
 * console.log(ASSET_BOUNDARIES[0].filename); // "DOOM.EXE"
 * ```
 */

import { resolve } from 'node:path';

const PROJECT_ROOT_PATH = resolve(import.meta.dir, '..', '..');

/** License category for a reference bundle file. */
export type LicenseCategory = 'commercial-shareware' | 'gpl' | 'mixed' | 'utility';

/** Whether a reference file may be redistributed within this project's output. */
export type RedistributionPolicy = 'forbidden' | 'permitted-with-notice';

/** Classification of a single reference bundle file. */
export interface AssetBoundary {
  /** File basename within the reference bundle. */
  readonly filename: string;
  /** License category governing this file. */
  readonly licenseCategory: LicenseCategory;
  /** Whether this file may be included in the codex package output. */
  readonly redistributionPolicy: RedistributionPolicy;
  /** Short explanation of the license status. */
  readonly licenseNote: string;
}

/**
 * Frozen, ASCIIbetically sorted classifications for all 8 reference
 * bundle files.  Commercial-shareware and mixed files are forbidden
 * from redistribution; GPL and utility files are permitted with notice.
 */
export const ASSET_BOUNDARIES: readonly AssetBoundary[] = Object.freeze([
  Object.freeze({
    filename: 'DOOM.EXE',
    licenseCategory: 'mixed',
    redistributionPolicy: 'forbidden',
    licenseNote: 'Polyglot binary containing id Software shareware DOS code and GPL Chocolate Doom Windows code',
  } satisfies AssetBoundary),
  Object.freeze({
    filename: 'DOOM1.WAD',
    licenseCategory: 'commercial-shareware',
    redistributionPolicy: 'forbidden',
    licenseNote: 'id Software shareware IWAD; redistribution restricted by original license',
  } satisfies AssetBoundary),
  Object.freeze({
    filename: 'DOOMD.EXE',
    licenseCategory: 'commercial-shareware',
    redistributionPolicy: 'forbidden',
    licenseNote: 'Original DOOM for DOS shareware binary',
  } satisfies AssetBoundary),
  Object.freeze({
    filename: 'DOOMDUPX.EXE',
    licenseCategory: 'commercial-shareware',
    redistributionPolicy: 'forbidden',
    licenseNote: 'UPX-packed original DOOM DOS binary',
  } satisfies AssetBoundary),
  Object.freeze({
    filename: 'DOOMWUPX.exe',
    licenseCategory: 'gpl',
    redistributionPolicy: 'permitted-with-notice',
    licenseNote: 'UPX-packed Chocolate Doom Windows binary; GPL v2+',
  } satisfies AssetBoundary),
  Object.freeze({
    filename: 'chocolate-doom.cfg',
    licenseCategory: 'gpl',
    redistributionPolicy: 'permitted-with-notice',
    licenseNote: 'Chocolate Doom host configuration; GPL v2+',
  } satisfies AssetBoundary),
  Object.freeze({
    filename: 'default.cfg',
    licenseCategory: 'gpl',
    redistributionPolicy: 'permitted-with-notice',
    licenseNote: 'Vanilla DOOM defaults generated by Chocolate Doom; GPL v2+',
  } satisfies AssetBoundary),
  Object.freeze({
    filename: 'smash.py',
    licenseCategory: 'utility',
    redistributionPolicy: 'permitted-with-notice',
    licenseNote: 'Binary merge utility by the bundle author',
  } satisfies AssetBoundary),
]);

/**
 * Absolute path to the read-only reference bundle checked into this
 * workspace under `doom/`.
 */
export const REFERENCE_BUNDLE_PATH = resolve(PROJECT_ROOT_PATH, 'doom');

/**
 * Absolute path to the writable codex workspace.
 * All derived artifacts, captures, and output must stay under this root.
 */
export const CODEX_WORKSPACE_PATH = PROJECT_ROOT_PATH;
