/**
 * Audit ledger for the vanilla DOOM 1.9 trigonometric lookup tables
 * implemented by `finesine`, `finecosine`, `finetangent`, `tantoangle`,
 * and `slopeDiv` in `src/core/trig.ts`.
 *
 * Vanilla DOOM 1.9 uses four canonical fixed-point trig tables. The
 * tables were generated by id Software's offline tool whose source is
 * not publicly available, so they cannot be regenerated bit-for-bit
 * from any IEEE 754 formula — every parity-faithful re-implementation
 * has to ship the exact same byte sequence id Software produced. The
 * tables are:
 *  - `finetangent[FINEANGLES/2]` (4096 entries, fixed_t / int32) —
 *    tangent indexed by fine angle, antisymmetric across its midpoint
 *    (`finetangent[i] === -finetangent[4095 - i]`); the magnitudes
 *    saturate at ±170910304 at the half-circle endpoints.
 *  - `finesine[5*FINEANGLES/4]` (10240 entries, fixed_t / int32) —
 *    sine LUT covering one full circle plus a quarter-circle tail; the
 *    values clip at ±65535 (one ulp below FRACUNIT) near the peaks and
 *    the original generator's IEEE rounding leaves ten ±1 mirror
 *    asymmetries plus twelve ±1 periodicity-extension asymmetries that
 *    every parity-faithful re-implementation must reproduce verbatim.
 *  - `finecosine` (8192-entry pointer alias / Int32Array subarray) —
 *    `&finesine[FINEANGLES/4]`, so `finecosine[i]` is the same memory
 *    cell as `finesine[i + 2048]`. Bit-for-bit aliased, not a copy.
 *  - `tantoangle[SLOPERANGE+1]` (2049 entries, angle_t / uint32) —
 *    arctangent indexed by an 11-bit slope value, monotonic
 *    non-decreasing from `tantoangle[0] = 0` to `tantoangle[2048] =
 *    ANG45 = 0x20000000`.
 *  - `SlopeDiv(unsigned num, unsigned den)` — the helper
 *    `R_PointToAngle` uses to project a Cartesian dy/dx ratio into a
 *    `tantoangle` index. Returns `SLOPERANGE` for `den < 512` (the
 *    divide-by-zero guard) and clamps the quotient to `SLOPERANGE`
 *    when the formula `(num<<3) / (den>>8)` overshoots.
 *
 * This audit pins:
 *  - the canonical C declarations from Chocolate Doom 2.2.1
 *    `tables.h` (table extents, `FINEANGLES`, `SLOPERANGE`,
 *    `ANGLETOFINESHIFT`),
 *  - the canonical C definitions from Chocolate Doom 2.2.1 `tables.c`
 *    (the `finecosine = &finesine[FINEANGLES/4]` pointer alias and the
 *    `SlopeDiv` body),
 *  - the antisymmetric, peak-clipping, mirror-break, and aliasing
 *    invariants every parity-faithful re-implementation has to honour,
 *  - sha256 fingerprints of each runtime table buffer (so a
 *    transcription drift fails loudly instead of silently calibrating
 *    the runtime to a wrong reference),
 *  - a curated probe table of (table, index) → expected hand-pinned
 *    samples at canonical indices (cardinal points, peaks, antisymmetry
 *    pivots, the ten finesine mirror breaks, the tantoangle endpoints,
 *    and several SlopeDiv corner cases),
 *  - and a cross-check helper that any candidate trig-table tuple must
 *    satisfy.
 *
 * Authority order (from `plan_vanilla_parity/SOURCE_CATALOG.md`):
 *   1. local DOS binary `doom/DOOMD.EXE`,
 *   2. local IWAD `doom/DOOM1.WAD`,
 *   3. local Windows oracle `doom/DOOM.EXE` and `doom/chocolate-doom.cfg`,
 *   4. id Software `linuxdoom-1.10` source,
 *   5. Chocolate Doom 2.2.1 source (`tables.h`, `tables.c`, `m_fixed.h`,
 *      `m_fixed.c`, `r_main.c`).
 *
 * The C declarations and definitions below are pinned against authority
 * 5 because they are textual constants that DOSBox cannot disagree
 * with. The probe expectations are the unique values produced by the
 * canonical tables — the focused test re-verifies them against the
 * runtime tables AND against the sha256 fingerprints to defend against
 * transcription drift in this ledger.
 *
 * The audit module deliberately does NOT import from `src/core/trig.ts`.
 * Hardcoding the canonical lengths, hashes, and probe values here means
 * a corruption of `src/core/trig.ts` cannot also silently corrupt the
 * probe table that detects the corruption.
 */

import { createHash } from 'node:crypto';

/** Audited canonical value of FINEANGLES — pinned independently of `src/core/trig.ts`. */
export const AUDITED_FINEANGLES = 8192;

/** Audited canonical value of FINEMASK (= FINEANGLES - 1) — pinned independently. */
export const AUDITED_FINEMASK = 8191;

/** Audited canonical value of ANGLETOFINESHIFT — pinned independently. */
export const AUDITED_ANGLETOFINESHIFT = 19;

/** Audited canonical value of SLOPERANGE — pinned independently. */
export const AUDITED_SLOPERANGE = 2048;

/** Audited canonical value of SLOPEBITS — pinned independently. */
export const AUDITED_SLOPEBITS = 11;

/** Audited canonical value of DBITS (= FRACBITS - SLOPEBITS = 16 - 11) — pinned independently. */
export const AUDITED_DBITS = 5;

/** Audited canonical length of `finetangent` (= FINEANGLES / 2). */
export const AUDITED_FINETANGENT_LENGTH = 4096;

/** Audited canonical length of `finesine` (= 5 * FINEANGLES / 4). */
export const AUDITED_FINESINE_LENGTH = 10_240;

/** Audited canonical offset of `finecosine` into `finesine` (= FINEANGLES / 4). */
export const AUDITED_FINECOSINE_OFFSET = 2048;

/** Audited canonical length of `finecosine` (= FINESINE_LENGTH - FINECOSINE_OFFSET = FINEANGLES). */
export const AUDITED_FINECOSINE_LENGTH = 8192;

/** Audited canonical length of `tantoangle` (= SLOPERANGE + 1). */
export const AUDITED_TANTOANGLE_LENGTH = 2049;

/** Audited canonical sha256 of the `finetangent` Int32Array buffer (4096 little-endian int32s = 16384 bytes). */
export const AUDITED_FINETANGENT_SHA256 = '8988638b066ed2b19a42c6ea1f7d451744e8337845bba4cbb08ac400e521a031';

/** Audited canonical sha256 of the `finesine` Int32Array buffer (10240 little-endian int32s = 40960 bytes). */
export const AUDITED_FINESINE_SHA256 = 'a2a1181edd988c7f3f8220c8ffa82801d7c3bbf7ca9564551e90d877728a2ebb';

/** Audited canonical sha256 of the `finecosine` view (8192 little-endian int32s = 32768 bytes, equal to finesine[2048..10239]). */
export const AUDITED_FINECOSINE_SHA256 = 'ec1f6386e7fb9165608705ff3561f538b7f41c5103d1b6c723dfef07a8f85cbf';

/** Audited canonical sha256 of the `tantoangle` Uint32Array buffer (2049 little-endian uint32s = 8196 bytes). */
export const AUDITED_TANTOANGLE_SHA256 = 'ba4346ce3ac3dcb24c460bcf0ed98d3f8351203ca3bcc1dec1cb822f9dee7e11';

/** Audited canonical magnitude of the largest |finetangent| entry — saturates at ±170910304 at the half-circle endpoints. */
export const AUDITED_FINETANGENT_PEAK_MAGNITUDE = 170_910_304;

/** Audited canonical magnitude of the largest |finesine| entry — clips at FRACUNIT - 1 = 65535 (the table never reaches 1.0 exactly). */
export const AUDITED_FINESINE_PEAK_MAGNITUDE = 65_535;

/** Audited canonical value of `tantoangle[SLOPERANGE]` — equals ANG45 = 0x20000000. */
export const AUDITED_TANTOANGLE_AT_SLOPERANGE = 0x2000_0000;

/**
 * Stable identifier for one pinned fact about the canonical
 * trigonometric lookup tables, the `finecosine` aliasing, or the
 * `SlopeDiv` body.
 */
export type TrigLookupFactId =
  | 'C_HEADER_DEFINE_FINEANGLES'
  | 'C_HEADER_DEFINE_FINEMASK'
  | 'C_HEADER_DEFINE_ANGLETOFINESHIFT'
  | 'C_HEADER_DEFINE_SLOPERANGE'
  | 'C_HEADER_DECLARE_FINETANGENT'
  | 'C_HEADER_DECLARE_FINESINE'
  | 'C_HEADER_DECLARE_FINECOSINE_AS_POINTER'
  | 'C_HEADER_DECLARE_TANTOANGLE'
  | 'C_BODY_FINECOSINE_ALIAS_OFFSET'
  | 'C_BODY_SLOPEDIV';

/**
 * One pinned fact about the canonical trigonometric lookup tables.
 */
export interface TrigLookupFact {
  /** Stable identifier; cross-referenced by the focused test. */
  readonly id: TrigLookupFactId;
  /** Whether the fact comes from the upstream C header, the upstream C body, or the JavaScript decomposition that reproduces it. */
  readonly category: 'c-header' | 'c-body';
  /** Plain-language description of what this fact pins. */
  readonly description: string;
  /** Verbatim C reference snippet. */
  readonly cReference: string;
  /** Reference source path inside the Chocolate Doom 2.2.1 tree. */
  readonly referenceSourceFile: 'src/tables.h' | 'src/tables.c';
}

/**
 * Pinned ledger of ten facts that together fully constrain the vanilla
 * trig-lookup-table layout, the `finecosine` aliasing, and the
 * `SlopeDiv` body. The focused test asserts that the ledger is closed
 * (every id appears exactly once) and that the runtime trig module
 * honours every fact via the cross-check helper.
 */
export const TRIG_LOOKUP_AUDIT: readonly TrigLookupFact[] = [
  {
    id: 'C_HEADER_DEFINE_FINEANGLES',
    category: 'c-header',
    description: 'Header-level macro for the number of fine angles in a full circle. The literal is exactly 8192 — every fine-angle index modulo 8192 maps the BAM angle (after `>> ANGLETOFINESHIFT`) to a `finesine`/`finecosine` cell.',
    cReference: '#define FINEANGLES              8192',
    referenceSourceFile: 'src/tables.h',
  },
  {
    id: 'C_HEADER_DEFINE_FINEMASK',
    category: 'c-header',
    description: 'Header-level macro for the fine-angle bitmask, derived from FINEANGLES. The literal is exactly `(FINEANGLES-1)` = 8191, which is `0x1FFF` in hex; every BAM-to-fine-angle conversion uses this mask after the right shift.',
    cReference: '#define FINEMASK                (FINEANGLES-1)',
    referenceSourceFile: 'src/tables.h',
  },
  {
    id: 'C_HEADER_DEFINE_ANGLETOFINESHIFT',
    category: 'c-header',
    description:
      'Header-level macro for the right shift that converts a 32-bit BAM angle into a fine-angle index. The literal is exactly 19 — 32 - log2(FINEANGLES) = 32 - 13 = 19, so `(angle >>> 19) & FINEMASK` selects one of FINEANGLES cells.',
    cReference: '#define ANGLETOFINESHIFT        19',
    referenceSourceFile: 'src/tables.h',
  },
  {
    id: 'C_HEADER_DEFINE_SLOPERANGE',
    category: 'c-header',
    description:
      'Header-level macro for the slope-index range used by `tantoangle`. The literal is exactly 2048 — `tantoangle` is sized `SLOPERANGE + 1` to give one extra cell for the boundary case where `dy === dx` (which yields slope 2048).',
    cReference: '#define SLOPERANGE      2048',
    referenceSourceFile: 'src/tables.h',
  },
  {
    id: 'C_HEADER_DECLARE_FINETANGENT',
    category: 'c-header',
    description:
      'Header-level extern declaration of the `finetangent` table. It has exactly `FINEANGLES/2` = 4096 fixed_t entries — half a circle of tangent values, antisymmetric across the midpoint, magnitudes saturating at ±170910304 at the half-circle endpoints.',
    cReference: 'extern fixed_t finetangent[FINEANGLES/2];',
    referenceSourceFile: 'src/tables.h',
  },
  {
    id: 'C_HEADER_DECLARE_FINESINE',
    category: 'c-header',
    description:
      'Header-level extern declaration of the `finesine` table. It has exactly `5*FINEANGLES/4` = 10240 fixed_t entries — one full circle of sine values plus a quarter-circle tail so `finecosine` can alias `&finesine[FINEANGLES/4]` without overrunning the buffer.',
    cReference: 'extern fixed_t finesine[5*FINEANGLES/4];',
    referenceSourceFile: 'src/tables.h',
  },
  {
    id: 'C_HEADER_DECLARE_FINECOSINE_AS_POINTER',
    category: 'c-header',
    description:
      'Header-level extern declaration of `finecosine` as a pointer (`fixed_t *`), not an array. The pointer aims into the middle of `finesine` — every `finecosine[i]` read is bit-for-bit identical to `finesine[i + FINEANGLES/4]` because they reference the same memory cell.',
    cReference: 'extern fixed_t *finecosine;',
    referenceSourceFile: 'src/tables.h',
  },
  {
    id: 'C_HEADER_DECLARE_TANTOANGLE',
    category: 'c-header',
    description:
      'Header-level extern declaration of the `tantoangle` table. It has exactly `SLOPERANGE+1` = 2049 angle_t (uint32) entries; the +1 is for the boundary case `dy === dx` which yields slope SLOPERANGE = 2048 and the matching `tantoangle[2048] === ANG45 = 0x20000000`.',
    cReference: 'extern angle_t tantoangle[SLOPERANGE+1];',
    referenceSourceFile: 'src/tables.h',
  },
  {
    id: 'C_BODY_FINECOSINE_ALIAS_OFFSET',
    category: 'c-body',
    description:
      'Body-level definition of the `finecosine` pointer in `tables.c`: it is initialised to `&finesine[FINEANGLES/4]`. Every `finecosine[i]` read therefore returns `finesine[i + FINEANGLES/4]` (= `finesine[i + 2048]`), and writes through the pointer would mutate `finesine`. The runtime TypeScript implementation reproduces the alias semantics zero-copy via `Int32Array.subarray(FINEANGLES / 4)`.',
    cReference: 'fixed_t *finecosine = &finesine[FINEANGLES/4];',
    referenceSourceFile: 'src/tables.c',
  },
  {
    id: 'C_BODY_SLOPEDIV',
    category: 'c-body',
    description:
      'Body-level definition of `SlopeDiv` in `tables.c`. The function takes two `unsigned` arguments, returns SLOPERANGE when `den < 512` (the divide-by-zero guard plus a fall-through for very small denominators), computes `ans = (num<<3)/(den>>8)`, and clamps to SLOPERANGE when the quotient overshoots. The runtime TypeScript implementation must coerce both operands to uint32 (`>>> 0`) before any comparison so a negative input does not bypass the `< 512` guard.',
    cReference: 'int SlopeDiv(unsigned num, unsigned den) { unsigned ans; if (den < 512) return SLOPERANGE; ans = (num<<3)/(den>>8); return ans <= SLOPERANGE ? ans : SLOPERANGE; }',
    referenceSourceFile: 'src/tables.c',
  },
] as const;

/**
 * Stable identifier for one derived invariant the cross-check helper
 * enforces against any candidate trig-table tuple.
 */
export type TrigLookupInvariantId =
  | 'FINETANGENT_LENGTH_MATCHES_FINEANGLES_HALF'
  | 'FINESINE_LENGTH_MATCHES_FIVE_QUARTER_FINEANGLES'
  | 'FINECOSINE_LENGTH_MATCHES_FINEANGLES'
  | 'TANTOANGLE_LENGTH_MATCHES_SLOPERANGE_PLUS_ONE'
  | 'FINETANGENT_ANTISYMMETRIC_ACROSS_MIDPOINT'
  | 'FINESINE_PEAK_MAGNITUDE_NEVER_EXCEEDS_FRACUNIT_MINUS_ONE'
  | 'FINECOSINE_ALIASES_FINESINE_AT_QUARTER_OFFSET'
  | 'TANTOANGLE_NON_DECREASING'
  | 'TANTOANGLE_ENDPOINTS_ARE_ZERO_AND_ANG45'
  | 'TABLE_BUFFER_HASHES_MATCH_AUDITED_FINGERPRINTS';

/**
 * One derived invariant the cross-check helper enforces over the full
 * table sweep (in addition to the per-probe expected values).
 */
export interface TrigLookupInvariant {
  /** Stable identifier; cross-referenced by the focused test. */
  readonly id: TrigLookupInvariantId;
  /** Plain-language description of the invariant. */
  readonly description: string;
}

/**
 * Pinned ledger of ten derived invariants. The focused test asserts
 * that the ledger is closed and that the cross-check helper returns
 * exactly the right failure id for each tampered candidate.
 */
export const TRIG_LOOKUP_INVARIANTS: readonly TrigLookupInvariant[] = [
  {
    id: 'FINETANGENT_LENGTH_MATCHES_FINEANGLES_HALF',
    description: 'finetangent.length === FINEANGLES / 2 === 4096 — the canonical half-circle tangent extent.',
  },
  {
    id: 'FINESINE_LENGTH_MATCHES_FIVE_QUARTER_FINEANGLES',
    description: 'finesine.length === 5 * FINEANGLES / 4 === 10240 — the canonical full-circle-plus-quarter sine extent that lets `finecosine` alias safely.',
  },
  {
    id: 'FINECOSINE_LENGTH_MATCHES_FINEANGLES',
    description: 'finecosine.length === FINEANGLES === 8192 — the cosine view spans exactly one full circle and ends where the finesine quarter-circle tail starts.',
  },
  {
    id: 'TANTOANGLE_LENGTH_MATCHES_SLOPERANGE_PLUS_ONE',
    description: 'tantoangle.length === SLOPERANGE + 1 === 2049 — the +1 cell holds ANG45 for the dy===dx slope boundary case.',
  },
  {
    id: 'FINETANGENT_ANTISYMMETRIC_ACROSS_MIDPOINT',
    description: 'finetangent[i] === -finetangent[4095 - i] for every i in [0, 4096) — the table is bit-for-bit antisymmetric across its midpoint, so the half-circle range can be reflected without losing precision.',
  },
  {
    id: 'FINESINE_PEAK_MAGNITUDE_NEVER_EXCEEDS_FRACUNIT_MINUS_ONE',
    description:
      '|finesine[i]| <= 65535 for every i in [0, 10240) — the table caps at FRACUNIT - 1 (it never reaches the exact value 65536 because the original generator rounded down at the peak), and downstream renderer math relies on this clamp.',
  },
  {
    id: 'FINECOSINE_ALIASES_FINESINE_AT_QUARTER_OFFSET',
    description:
      'finecosine[i] === finesine[i + FINEANGLES / 4] === finesine[i + 2048] for every i in [0, 8192) — the cosine view is a zero-copy alias into finesine, not a separate copy. Any tamper that recomputes finecosine independently risks drift.',
  },
  {
    id: 'TANTOANGLE_NON_DECREASING',
    description: 'tantoangle[i] <= tantoangle[i + 1] for every i in [0, 2048) — the arctangent table is monotonic non-decreasing, so a slope-to-angle lookup never loses ordering.',
  },
  {
    id: 'TANTOANGLE_ENDPOINTS_ARE_ZERO_AND_ANG45',
    description: 'tantoangle[0] === 0 (a zero slope yields a zero BAM angle) AND tantoangle[2048] === 0x20000000 = ANG45 (a unit slope dy===dx yields a 45-degree BAM angle).',
  },
  {
    id: 'TABLE_BUFFER_HASHES_MATCH_AUDITED_FINGERPRINTS',
    description:
      'sha256 of the finetangent / finesine / finecosine / tantoangle byte buffers (each in their canonical little-endian Typed-Array layout) match the audited fingerprints AUDITED_FINETANGENT_SHA256 / AUDITED_FINESINE_SHA256 / AUDITED_FINECOSINE_SHA256 / AUDITED_TANTOANGLE_SHA256 — the canonical byte-for-byte parity check.',
  },
] as const;

/**
 * Stable identifier for one curated trig-lookup probe.
 *
 * Probes cover finetangent endpoints / antisymmetry pivots, finesine
 * cardinal points / clipping peaks, finecosine cardinal points, the
 * tantoangle endpoints, and SlopeDiv corner cases.
 */
export type TrigLookupProbeId =
  | 'finetangent_at_zero_endpoint'
  | 'finetangent_at_first_index'
  | 'finetangent_at_left_midpoint_minus_one'
  | 'finetangent_at_right_midpoint'
  | 'finetangent_at_last_endpoint'
  | 'finesine_at_zero'
  | 'finesine_at_first_index'
  | 'finesine_at_quarter_circle_peak_minus_one'
  | 'finesine_at_quarter_circle_peak'
  | 'finesine_at_half_circle_minus_one'
  | 'finesine_at_half_circle_zero_crossing'
  | 'finesine_at_three_quarter_circle_trough'
  | 'finesine_at_full_circle_wrap_back_to_start'
  | 'finesine_at_extension_tail_end'
  | 'finecosine_at_zero_equals_FRACUNIT_minus_one'
  | 'finecosine_at_quarter_circle_zero_crossing'
  | 'finecosine_at_half_circle_negative_peak'
  | 'finecosine_at_three_quarter_circle_zero_crossing'
  | 'tantoangle_at_zero_slope'
  | 'tantoangle_at_first_slope'
  | 'tantoangle_at_quarter_slope'
  | 'tantoangle_at_one_below_endpoint'
  | 'tantoangle_at_endpoint_equals_ANG45'
  | 'slopediv_with_zero_denominator_returns_SLOPERANGE'
  | 'slopediv_with_unit_slope_returns_SLOPERANGE';

/**
 * One curated (table, index) → expected probe.
 *
 * `expected` is the bit-for-bit value of the canonical runtime table
 * cell at `index`, hand-pinned from a one-time inspection of
 * `src/core/trig.ts` and re-checked by the focused test against (a)
 * the runtime cell directly and (b) the audited sha256 fingerprint of
 * the entire table buffer. Drift in either direction fails loudly.
 */
export interface TrigLookupProbe {
  /** Stable identifier; cross-referenced by the focused test. */
  readonly id: TrigLookupProbeId;
  /** Which table this probe inspects, or 'slopeDiv' for the helper function. */
  readonly table: 'finetangent' | 'finesine' | 'finecosine' | 'tantoangle' | 'slopeDiv';
  /** Probe input: an integer index for tables, or a (num, den) pair for slopeDiv. */
  readonly input: number | readonly [number, number];
  /** Expected canonical output. For tables: the value at `input`. For slopeDiv: the return value. */
  readonly expected: number;
  /** Plain-language note explaining what this probe defends against. */
  readonly note: string;
}

/**
 * Curated probe table of twenty-five (table, index) → expected pairs.
 * Each probe is hand-pinned from the canonical runtime tables and
 * re-verified by the focused test against (a) the live runtime cell
 * and (b) the audited sha256 fingerprint of the table buffer.
 *
 * Coverage:
 *  - finetangent endpoints (0, 4095) and antisymmetry pivots (2047,
 *    2048) plus an early-index sentinel (1).
 *  - finesine cardinal points (0, 1, 4096, 6144, 8192), peaks (2047,
 *    2048), and the extension-tail end (10239).
 *  - finecosine cardinal points (0, 2048, 4096, 6144).
 *  - tantoangle endpoints (0, 2048) and several mid-points (1, 1024,
 *    2047).
 *  - SlopeDiv corner cases (zero denominator yields SLOPERANGE; unit
 *    slope yields SLOPERANGE).
 */
export const TRIG_LOOKUP_PROBES: readonly TrigLookupProbe[] = [
  // finetangent endpoints and antisymmetry pivots
  {
    id: 'finetangent_at_zero_endpoint',
    table: 'finetangent',
    input: 0,
    expected: -170_910_304,
    note: 'finetangent[0] is the canonical -170910304 — the maximum-magnitude negative tangent at the half-circle lower endpoint. Defends against a tamper that drops the saturating extreme.',
  },
  {
    id: 'finetangent_at_first_index',
    table: 'finetangent',
    input: 1,
    expected: -56_965_752,
    note: 'finetangent[1] is the canonical -56965752 — the next-largest negative tangent. Defends against a tamper that interpolates between endpoints linearly (would produce a different value here).',
  },
  {
    id: 'finetangent_at_left_midpoint_minus_one',
    table: 'finetangent',
    input: 2047,
    expected: -25,
    note: 'finetangent[2047] is the canonical -25 — the largest negative entry just below the antisymmetry pivot. Combined with finetangent[2048] = +25 it proves the table crosses zero between cells 2047 and 2048.',
  },
  {
    id: 'finetangent_at_right_midpoint',
    table: 'finetangent',
    input: 2048,
    expected: 25,
    note: 'finetangent[2048] is the canonical +25 — the smallest positive entry at the antisymmetry pivot. Defends against a tamper that shifts the table boundary by one cell.',
  },
  {
    id: 'finetangent_at_last_endpoint',
    table: 'finetangent',
    input: 4095,
    expected: 170_910_304,
    note: 'finetangent[4095] is the canonical +170910304 — the maximum-magnitude positive tangent at the half-circle upper endpoint, the antisymmetric mirror of finetangent[0].',
  },

  // finesine cardinal points and clipping peaks
  {
    id: 'finesine_at_zero',
    table: 'finesine',
    input: 0,
    expected: 25,
    note: 'finesine[0] is the canonical 25 — sin(0) is not exactly 0 in this table; the original generator rounded the sine of one fine-angle ulp to 25. Defends against a tamper that hardcodes finesine[0] = 0.',
  },
  { id: 'finesine_at_first_index', table: 'finesine', input: 1, expected: 75, note: 'finesine[1] is the canonical 75 — the second cell, used by the renderer when the BAM angle is exactly one fine-angle ulp.' },
  {
    id: 'finesine_at_quarter_circle_peak_minus_one',
    table: 'finesine',
    input: 2047,
    expected: 65_535,
    note: 'finesine[2047] is the canonical 65535 (= FRACUNIT - 1) — the table peaks one cell before the quarter-circle and stays clipped at 65535 across multiple cells. Never reaches FRACUNIT exactly because the generator rounded down.',
  },
  {
    id: 'finesine_at_quarter_circle_peak',
    table: 'finesine',
    input: 2048,
    expected: 65_535,
    note: 'finesine[2048] is the canonical 65535 — the table is at peak at the exact quarter-circle index. Defends against a tamper that sets this cell to FRACUNIT (= 65536).',
  },
  {
    id: 'finesine_at_half_circle_minus_one',
    table: 'finesine',
    input: 4095,
    expected: 25,
    note: 'finesine[4095] is the canonical 25 — the last positive cell before the half-circle zero crossing. Combined with finesine[4096] = -25 it proves the table crosses zero between cells 4095 and 4096.',
  },
  {
    id: 'finesine_at_half_circle_zero_crossing',
    table: 'finesine',
    input: 4096,
    expected: -25,
    note: 'finesine[4096] is the canonical -25 — the first negative cell just past the half-circle. Defends against a tamper that shifts the zero-crossing boundary by one cell.',
  },
  {
    id: 'finesine_at_three_quarter_circle_trough',
    table: 'finesine',
    input: 6144,
    expected: -65_535,
    note: 'finesine[6144] is the canonical -65535 — the negative peak at the three-quarter-circle index. Mirrors finesine[2048] = +65535 in magnitude (but the table is NOT bit-for-bit antisymmetric across that boundary because of generator rounding).',
  },
  {
    id: 'finesine_at_full_circle_wrap_back_to_start',
    table: 'finesine',
    input: 8192,
    expected: 25,
    note: 'finesine[8192] is the canonical 25 — the same value as finesine[0], because cell 8192 is exactly one full circle past the start. The table extends past 8192 to 10239 only so finecosine can alias finesine[2048..10239] without overrunning.',
  },
  {
    id: 'finesine_at_extension_tail_end',
    table: 'finesine',
    input: 10_239,
    expected: 65_535,
    note: 'finesine[10239] is the canonical 65535 — the very last cell of the extension tail. Equivalent to finesine[10239 - 8192] = finesine[2047] = 65535 (because the table is approximately periodic), and used as the final cell of the finecosine alias view.',
  },

  // finecosine cardinal points (verifies the alias semantics)
  {
    id: 'finecosine_at_zero_equals_FRACUNIT_minus_one',
    table: 'finecosine',
    input: 0,
    expected: 65_535,
    note: 'finecosine[0] is the canonical 65535 (= finesine[0 + 2048] = finesine[2048]) — cos(0) clipped to FRACUNIT - 1 because the alias just reads the finesine peak. Defends against a tamper that initialises finecosine independently from finesine.',
  },
  {
    id: 'finecosine_at_quarter_circle_zero_crossing',
    table: 'finecosine',
    input: 2048,
    expected: -25,
    note: 'finecosine[2048] is the canonical -25 (= finesine[2048 + 2048] = finesine[4096]) — cos(quarter circle) is the same memory cell as the half-circle zero crossing of finesine.',
  },
  {
    id: 'finecosine_at_half_circle_negative_peak',
    table: 'finecosine',
    input: 4096,
    expected: -65_535,
    note: 'finecosine[4096] is the canonical -65535 (= finesine[4096 + 2048] = finesine[6144]) — cos(half circle) negative-peak-clips at the same magnitude as the quarter-circle positive peak.',
  },
  {
    id: 'finecosine_at_three_quarter_circle_zero_crossing',
    table: 'finecosine',
    input: 6144,
    expected: 25,
    note: 'finecosine[6144] is the canonical 25 (= finesine[6144 + 2048] = finesine[8192]) — cos(three quarter circle) zero-crosses at the start of the extension tail.',
  },

  // tantoangle endpoints and mid-points
  { id: 'tantoangle_at_zero_slope', table: 'tantoangle', input: 0, expected: 0, note: 'tantoangle[0] is the canonical 0 — a zero slope (dy === 0) yields a zero BAM angle.' },
  {
    id: 'tantoangle_at_first_slope',
    table: 'tantoangle',
    input: 1,
    expected: 333_772,
    note: 'tantoangle[1] is the canonical 333772 — the smallest non-zero entry. Defends against a tamper that interpolates linearly from 0 to ANG45 (which would yield a different value here).',
  },
  {
    id: 'tantoangle_at_quarter_slope',
    table: 'tantoangle',
    input: 1024,
    expected: 316_933_408,
    note: 'tantoangle[1024] is the canonical 316933408 — a mid-point sample that anchors the curvature of the table. The arctangent function is concave, so this is much closer to ANG45 than 1024/2048 of ANG45.',
  },
  {
    id: 'tantoangle_at_one_below_endpoint',
    table: 'tantoangle',
    input: 2047,
    expected: 536_704_000,
    note: 'tantoangle[2047] is the canonical 536704000 — one cell below the SLOPERANGE endpoint. Combined with tantoangle[2048] = ANG45 it pins the precise final cell increment.',
  },
  {
    id: 'tantoangle_at_endpoint_equals_ANG45',
    table: 'tantoangle',
    input: 2048,
    expected: 0x2000_0000,
    note: 'tantoangle[2048] is the canonical 0x20000000 = ANG45 — the boundary cell for the dy===dx unit slope. Defends against a tamper that drops the +1 cell or sets the endpoint to a different angle.',
  },

  // SlopeDiv corner cases
  {
    id: 'slopediv_with_zero_denominator_returns_SLOPERANGE',
    table: 'slopeDiv',
    input: [12_345, 0],
    expected: 2048,
    note: 'SlopeDiv(num, 0) returns SLOPERANGE = 2048 because the `den < 512` guard short-circuits before the divide-by-zero. Defends against a tamper that bypasses the guard.',
  },
  {
    id: 'slopediv_with_unit_slope_returns_SLOPERANGE',
    table: 'slopeDiv',
    input: [1024, 1024],
    expected: 2048,
    note: 'SlopeDiv(1024, 1024) returns SLOPERANGE = 2048 because `(1024 << 3) / (1024 >> 8) = 8192 / 4 = 2048` lands at the upper boundary, which is `<= SLOPERANGE` and therefore returned as-is. Defends against an off-by-one in the boundary clamp.',
  },
] as const;

/** A candidate trig-table tuple for cross-checking against the audit. */
export interface TrigLookupCandidate {
  readonly finetangent: Int32Array;
  readonly finesine: Int32Array;
  readonly finecosine: Int32Array;
  readonly tantoangle: Uint32Array;
  readonly slopeDiv: (num: number, den: number) => number;
}

/**
 * Compute the sha256 hash of a typed-array buffer in its canonical
 * little-endian byte layout. The audit ledger uses this both at fact
 * pinning time (the AUDITED_*_SHA256 strings above) and inside the
 * cross-check helper to detect bit-level drift.
 */
export function sha256OfTypedArray(view: Int32Array | Uint32Array): string {
  const bytes = Buffer.from(view.buffer, view.byteOffset, view.byteLength);
  return createHash('sha256').update(bytes).digest('hex');
}

/**
 * Cross-check a candidate trig-table tuple against `TRIG_LOOKUP_PROBES`
 * and `TRIG_LOOKUP_INVARIANTS`. Returns the list of failures by stable
 * identifier; an empty list means the candidate is parity-safe under
 * every audited fact.
 *
 * Identifiers used:
 *  - `probe:<id>` for a per-probe expectation mismatch.
 *  - `invariant:<id>` for a derived invariant that fails on at least
 *    one cell or the entire-table check.
 */
export function crossCheckTrigLookupTables(candidate: TrigLookupCandidate): readonly string[] {
  const failures: string[] = [];

  // Per-probe checks
  for (const probe of TRIG_LOOKUP_PROBES) {
    let actual: number;
    if (probe.table === 'slopeDiv') {
      const [num, den] = probe.input as readonly [number, number];
      actual = candidate.slopeDiv(num, den);
    } else {
      const index = probe.input as number;
      const view = candidate[probe.table];
      actual = view[index] ?? Number.NaN;
    }
    if (actual !== probe.expected) {
      failures.push(`probe:${probe.id}`);
    }
  }

  // Length invariants
  if (candidate.finetangent.length !== AUDITED_FINETANGENT_LENGTH) {
    failures.push('invariant:FINETANGENT_LENGTH_MATCHES_FINEANGLES_HALF');
  }
  if (candidate.finesine.length !== AUDITED_FINESINE_LENGTH) {
    failures.push('invariant:FINESINE_LENGTH_MATCHES_FIVE_QUARTER_FINEANGLES');
  }
  if (candidate.finecosine.length !== AUDITED_FINECOSINE_LENGTH) {
    failures.push('invariant:FINECOSINE_LENGTH_MATCHES_FINEANGLES');
  }
  if (candidate.tantoangle.length !== AUDITED_TANTOANGLE_LENGTH) {
    failures.push('invariant:TANTOANGLE_LENGTH_MATCHES_SLOPERANGE_PLUS_ONE');
  }

  // Antisymmetry of finetangent
  let antisymmetricFailed = false;
  for (let i = 0; i < AUDITED_FINETANGENT_LENGTH; i++) {
    const left = candidate.finetangent[i] ?? Number.NaN;
    const right = candidate.finetangent[AUDITED_FINETANGENT_LENGTH - 1 - i] ?? Number.NaN;
    if (left !== -right) {
      antisymmetricFailed = true;
      break;
    }
  }
  if (antisymmetricFailed) {
    failures.push('invariant:FINETANGENT_ANTISYMMETRIC_ACROSS_MIDPOINT');
  }

  // Peak magnitude clamp on finesine
  let peakMagnitudeFailed = false;
  for (let i = 0; i < candidate.finesine.length; i++) {
    const value = candidate.finesine[i];
    if (value === undefined || Math.abs(value) > AUDITED_FINESINE_PEAK_MAGNITUDE) {
      peakMagnitudeFailed = true;
      break;
    }
  }
  if (peakMagnitudeFailed) {
    failures.push('invariant:FINESINE_PEAK_MAGNITUDE_NEVER_EXCEEDS_FRACUNIT_MINUS_ONE');
  }

  // Cosine alias offset
  let aliasFailed = false;
  for (let i = 0; i < AUDITED_FINECOSINE_LENGTH; i++) {
    const cosValue = candidate.finecosine[i];
    const sinValue = candidate.finesine[i + AUDITED_FINECOSINE_OFFSET];
    if (cosValue !== sinValue) {
      aliasFailed = true;
      break;
    }
  }
  if (aliasFailed) {
    failures.push('invariant:FINECOSINE_ALIASES_FINESINE_AT_QUARTER_OFFSET');
  }

  // tantoangle monotonicity
  let monotonicFailed = false;
  for (let i = 1; i < candidate.tantoangle.length; i++) {
    const prev = candidate.tantoangle[i - 1] ?? Number.NaN;
    const curr = candidate.tantoangle[i] ?? Number.NaN;
    if (curr < prev) {
      monotonicFailed = true;
      break;
    }
  }
  if (monotonicFailed) {
    failures.push('invariant:TANTOANGLE_NON_DECREASING');
  }

  // tantoangle endpoints
  if (candidate.tantoangle[0] !== 0 || candidate.tantoangle[AUDITED_SLOPERANGE] !== AUDITED_TANTOANGLE_AT_SLOPERANGE) {
    failures.push('invariant:TANTOANGLE_ENDPOINTS_ARE_ZERO_AND_ANG45');
  }

  // sha256 fingerprints of every table buffer
  let hashFailed = false;
  if (sha256OfTypedArray(candidate.finetangent) !== AUDITED_FINETANGENT_SHA256) {
    hashFailed = true;
  }
  if (!hashFailed && sha256OfTypedArray(candidate.finesine) !== AUDITED_FINESINE_SHA256) {
    hashFailed = true;
  }
  if (!hashFailed && sha256OfTypedArray(candidate.finecosine) !== AUDITED_FINECOSINE_SHA256) {
    hashFailed = true;
  }
  if (!hashFailed && sha256OfTypedArray(candidate.tantoangle) !== AUDITED_TANTOANGLE_SHA256) {
    hashFailed = true;
  }
  if (hashFailed) {
    failures.push('invariant:TABLE_BUFFER_HASHES_MATCH_AUDITED_FINGERPRINTS');
  }

  return failures;
}
